# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check code style and conduct blackbox tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Check code style
        run: |
          pip install "yapf==0.30.0"
          bash format.sh --test
      - name: Blackbox tests
        run: |
          pwd
          pip install -e .
          pip install pytest
          cd pgdrive/tests/
          pytest -sv test_pgdrive_env.py